global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:8000"]
  - job_name: "kafka_exporter"
    static_configs:
      - targets: ["localhost:9308"]
  - job_name: "cockroachdb"
    scheme: https
    metrics_path: "/_status/vars"
    static_configs:
      - targets: ["geo-track-17821.j77.cockroachlabs.cloud"]
    tls_config:
      insecure_skip_verify: true
